### 회원가입
POST localhost:3000/users
Content-Type: application/json

{
  "name": "성민섭",
  "email": "ms_sh0728@naver.com",
  "password": "dkssudgktpdygg"
}

### 이메일
//curl -X POST http://127.0.0.1:3000/users/email-verify\?signupVerifyToken\=test_token
POST localhost:3000/users/email-verify
Content-Type: application/json

{
  "signupVerifyToken": "test_token"
}

### 로그인
POST localhost:3000/users/login
Content-Type: application/json

{
  "email": "ms_sh0728@naver.com",
  "password": "dkssudgktpdygg"
}

### 회원 정보 조회
GET localhost:3000/users/01GSPR1AW9H6J4F1TW7FYBKCBB
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxR1NQUjFBVzlINko0RjFUVzdGWUJLQ0JCIiwibmFtZSI6IuyEseuvvOyErSIsImVtYWlsIjoibXNfc2gwNzI4QG5hdmVyLmNvbSIsImlhdCI6MTY3Njg3OTg2NCwiZXhwIjoxNjc2OTY2MjY0LCJhdWQiOiJleGFtcGxlLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIn0.Aw_cynUp0vSIshcSZogT8YK7utTfGN158qNduSuuc5E


### 메일 인증
POST localhost:3000/users/
Content-Type: application/json

{
  "name": "성민섭",
  "email": "ms_sh0728@naver.com",
  "password": "asdf"
}

### Health-Check
GET http://localhost:3000/health-check
Content-Type: application/json